#!/bin/bash

# Get the current logged-in user
CURRENT_USER=$(/usr/bin/stat -f%Su /dev/console)

# Path to settings.json
SETTINGS_FILE="$HOME/Library/Application Support/WSO2 Integrator/User/settings.json"

# Replace <username> with the actual username
if [ -f "$SETTINGS_FILE" ]; then
    /usr/bin/sed -i '' "s/<username>/$CURRENT_USER/g" "$SETTINGS_FILE"
fi

exit 0
