#!/bin/bash
#
# Copyright (c) WSO2. All rights reserved.

# Remove symlinks
rm -f /usr/bin/wso2-integrator

# Remove environment variable file
rm -f /etc/profile.d/wso2.sh

# Uninstall the desktop entry
if hash update-desktop-database 2>/dev/null; then
	update-desktop-database
fi

# Update mimetype database for removed workspace mimetype
if hash update-mime-database 2>/dev/null; then
	update-mime-database /usr/share/mime
fi
