#!/usr/bin/env bash
#
# Copyright (c) WSO2. All rights reserved.
# Change ownership and permissions for integrator files
chown -R root:root /usr/share/wso2-integrator
chmod -R o+w /usr/share/wso2-integrator/components/icp/bin/database/
chmod -R o+rwx /usr/share/wso2-integrator/components/icp/www/public/
chmod 4755 /usr/share/wso2-integrator/chrome-sandbox 2>/dev/null || true

# Create symlinks to /usr/bin
rm -f /usr/bin/wso2-integrator
ln -s /usr/share/wso2-integrator/bin/wso2-integrator /usr/bin/wso2-integrator

# Register in the alternatives system
# Priority of 0 should never make wso2-integrator the default editor in auto mode
update-alternatives --install /usr/bin/editor editor /usr/bin/wso2-integrator 0

# Install the desktop entry
if hash update-desktop-database 2>/dev/null; then
	update-desktop-database
fi

# Update mimetype database to pickup workspace mimetype
if hash update-mime-database 2>/dev/null; then
	update-mime-database /usr/share/mime
fi