#!/usr/bin/env bash
#
# Copyright (c) WSO2. All rights reserved.

# Deregister wso2-integrator from the alternatives system
if update-alternatives --display editor >/dev/null 2>&1; then
	update-alternatives --remove editor /usr/bin/@SLUG@ || true
fi