import { PrebuiltIntegration } from "@wso2/wi-core";

// Replace when exposed with cdn
export const BI_PREBUILT_INTEGRATIONS: PrebuiltIntegration[] = [
    {
      "displayName": "Export Salesforce Opportunities to a Google Sheet",
      "description": "Periodically exports all Salesforce Opportunities to a Google Sheet.",
      "componentType": "scheduled-task",
      "buildPack": "ballerina",
      "repositoryUrl": "https://github.com/wso2/integration-samples/",
      "branch": "main",
      "subDirectory": "/ballerina-integrator",
      "componentPath": "/salesforceops-to-googlesheets",
      "thumbnailPath": "",
      "documentationPath": "/ballerina-integrator/salesforceops-to-googlesheets/README.md",
      "applications": ["Salesforce", "Google Sheets"],
      "imageVersion": "1.0.0",
      "tags": ["Automation", "CRM"],
      "imageUrl": "wso2integrations.azurecr.io/salesforceops_to_googlesheets:0.1.0",
      "bidirectional": false
    },
    {
      "displayName": "Create Stripe Customer when a new Shopify Customer is Created",
      "description": "This webhook-based Integration as API listens for new customer creation events in Shopify and creates a corresponding customer in Stripe.",
      "componentType": "service",
      "buildPack": "ballerina",
      "repositoryUrl": "https://github.com/wso2/integration-samples/",
      "branch": "main",
      "subDirectory": "/ballerina-integrator",
      "componentPath": "/new-shopify-customer-to-stripe",
      "thumbnailPath": "",
      "documentationPath": "/ballerina-integrator/new-shopify-customer-to-stripe/README.md",
      "applications": ["Shopify", "Stripe"],
      "imageVersion": "1.0.0",
      "tags": ["HTTP", "REST", "CRM"],
      "imageUrl": "wso2integrations.azurecr.io/new_shopify_customer_to_stripe:0.2.0",
      "bidirectional": false
    },
    {
      "displayName": "Create Salesforce Contact and notify Google Chat",
      "description": "This Integration as API creates a new contact in Salesforce and sends a notification to a Google Chat space.",
      "componentType": "service",
      "buildPack": "ballerina",
      "repositoryUrl": "https://github.com/wso2/integration-samples/",
      "branch": "main",
      "subDirectory": "/ballerina-integrator",
      "componentPath": "/signup-sfchatsync",
      "thumbnailPath": "",
      "documentationPath": "/ballerina-integrator/signup-sfchatsync/README.md",
      "applications": ["Salesforce", "Google Chat"],
      "imageVersion": "1.0.0",
      "tags": ["HTTP", "REST", "CRM"],
      "imageUrl": "wso2integrations.azurecr.io/signup_sfchatsync:0.1.0",
      "bidirectional": true
    },
    {
      "displayName": "Send a Google Chat message when a GitHub issue is created",
      "description": "When an issue is labeled in GitHub, this integration sends a message to a Google Chat space with the issue details.",
      "componentType": "service",
      "buildPack": "ballerina",
      "repositoryUrl": "https://github.com/wso2/integration-samples/",
      "branch": "main",
      "subDirectory": "/ballerina-integrator",
      "componentPath": "/github-issue-to-google-chat",
      "thumbnailPath": "",
      "documentationPath": "/ballerina-integrator/github-issue-to-google-chat/README.md",
      "applications": ["GitHub", "Google Chat"],
      "imageVersion": "0.1.0",
      "tags": [],
      "imageUrl": "wso2integrations.azurecr.io/github_issue_to_google_chat:0.2.0",
      "defaultPackage": "wso2/github_issue_to_google_chat",
      "bidirectional": false
    },
    {
      "displayName": "Send a Slack Message When a Salesforce Opportunity is Closed-Won",
      "description": "When a Salesforce opportunity is marked as Closed-Won, instantly send a congratulatory Slack message to your sales channel.",
      "componentType": "event-handler",
      "buildPack": "ballerina",
      "repositoryUrl": "https://github.com/wso2/integration-samples/",
      "branch": "main",
      "subDirectory": "/ballerina-integrator",
      "componentPath": "/salesforce-closed-won-slack-notifier",
      "thumbnailPath": "",
      "documentationPath": "/ballerina-integrator/salesforce-closed-won-slack-notifier/README.md",
      "applications": ["Salesforce", "Slack"],
      "imageVersion": "0.1.0",
      "tags": [],
      "imageUrl": "wso2integrations.azurecr.io/salesforce_closed_won_slack_notifier:0.1.0",
      "defaultPackage": "wso2/salesforce_closed_won_slack_notifier",
      "bidirectional": false
    },
    {
      "displayName": "Send a Salesforce Performance Summary to Email",
      "description": "On a given schedule, compile Salesforce sales performance metrics and deliver a summary report via email.",
      "componentType": "scheduled-task",
      "buildPack": "ballerina",
      "repositoryUrl": "https://github.com/wso2/integration-samples/",
      "branch": "main",
      "subDirectory": "/ballerina-integrator",
      "componentPath": "/salesforce-performance-summary-to-email",
      "thumbnailPath": "",
      "documentationPath": "/ballerina-integrator/salesforce-performance-summary-to-email/README.md",
      "applications": ["Salesforce", "Mailchimp"],
      "imageVersion": "0.1.0",
      "tags": [],
      "imageUrl": "wso2integrations.azurecr.io/salesforce_performance_summary_to_email:0.1.0",
      "defaultPackage": "wso2/salesforce_performance_summary_to_email",
      "bidirectional": false
    },
    {
      "displayName": "Send a Summary of Jira Tickets via Mailchimp Email",
      "description": "When scheduled, this fetches open Jira tickets and sends a formatted summary email via Mailchimp.",
      "componentType": "scheduled-task",
      "buildPack": "ballerina",
      "repositoryUrl": "https://github.com/wso2/integration-samples/",
      "branch": "main",
      "subDirectory": "/ballerina-integrator",
      "componentPath": "/jira-summary-mailchimp",
      "thumbnailPath": "",
      "documentationPath": "/ballerina-integrator/jira-summary-mailchimp/README.md",
      "applications": ["Jira", "Mailchimp"],
      "imageVersion": "0.1.0",
      "tags": [],
      "imageUrl": "wso2integrations.azurecr.io/jira_summary_mailchimp:0.1.0",
      "defaultPackage": "wso2/jira_summary_mailchimp",
      "bidirectional": false
    },
    {
      "displayName": "Send a message to a Slack channel when a Shopify order is made",
      "description": "When a new Shopify order is placed, automatically post an order notification message to a designated Slack channel.",
      "componentType": "service",
      "buildPack": "ballerina",
      "repositoryUrl": "https://github.com/wso2/integration-samples/",
      "branch": "main",
      "subDirectory": "/ballerina-integrator",
      "componentPath": "/new-shopify-order-to-slack",
      "thumbnailPath": "",
      "documentationPath": "/ballerina-integrator/new-shopify-order-to-slack/README.md",
      "applications": ["Shopify", "Slack"],
      "imageVersion": "0.1.0",
      "tags": [],
      "imageUrl": "wso2integrations.azurecr.io/new_shopify_order_to_slack:0.2.0",
      "defaultPackage": "wso2/new_shopify_order_to_slack",
      "bidirectional": false
    },
    {
      "displayName": "Update a Google Sheet When a Shopify Order is Created",
      "description": "When a new Shopify order is placed, automatically append the order details as a new row in a Google Sheet.",
      "componentType": "service",
      "buildPack": "ballerina",
      "repositoryUrl": "https://github.com/wso2/integration-samples/",
      "branch": "main",
      "subDirectory": "/ballerina-integrator",
      "componentPath": "/shopify-order-to-google-sheets",
      "thumbnailPath": "",
      "documentationPath": "/ballerina-integrator/shopify-order-to-google-sheets/README.md",
      "applications": ["Shopify", "Google Sheets"],
      "imageVersion": "0.1.0",
      "tags": [],
      "imageUrl": "wso2integrations.azurecr.io/shopify_order_to_google_sheets:0.2.0",
      "defaultPackage": "wso2/shopify_order_to_google_sheets",
      "bidirectional": false
    },
    {
      "displayName": "Create a Salesforce Contact When a New Shopify Customer Signs Up",
      "description": "When a new customer signs up on Shopify, automatically create a corresponding contact in Salesforce.",
      "componentType": "service",
      "buildPack": "ballerina",
      "repositoryUrl": "https://github.com/wso2/integration-samples/",
      "branch": "main",
      "subDirectory": "/ballerina-integrator",
      "componentPath": "/shopify-customer-to-salesforce",
      "thumbnailPath": "",
      "documentationPath": "/ballerina-integrator/shopify-customer-to-salesforce/README.md",
      "applications": ["Shopify", "Salesforce"],
      "imageVersion": "0.1.0",
      "tags": [],
      "imageUrl": "wso2integrations.azurecr.io/shopify_customer_to_salesforce:0.2.0",
      "defaultPackage": "wso2/shopify_customer_to_salesforce",
      "bidirectional": false
    },
    {
      "displayName": "Export Salesforce Leads to a Google Sheet",
      "description": "Periodically exports all Salesforce Leads to a Google Sheet.",
      "componentType": "scheduled-task",
      "buildPack": "ballerina",
      "repositoryUrl": "https://github.com/wso2/integration-samples/",
      "branch": "main",
      "subDirectory": "/ballerina-integrator",
      "componentPath": "/salesforce-leads-to-googlesheets",
      "thumbnailPath": "",
      "documentationPath": "/ballerina-integrator/salesforce-leads-to-googlesheets/README.md",
      "applications": ["Salesforce", "Google Sheets"],
      "imageVersion": "0.1.0",
      "tags": [],
      "imageUrl": "wso2integrations.azurecr.io/salesforce_leads_to_googlesheets:0.1.0",
      "defaultPackage": "wso2/salesforce_leads_to_googlesheets",
      "bidirectional": false
    },
    {
      "displayName": "Create a Transaction in QuickBooks When a Shopify Order is Completed",
      "description": "When a Shopify order is marked as completed, automatically create a corresponding transaction record in QuickBooks.",
      "componentType": "service",
      "buildPack": "ballerina",
      "repositoryUrl": "https://github.com/wso2/integration-samples/",
      "branch": "main",
      "subDirectory": "/ballerina-integrator",
      "componentPath": "/shopify-to-quickbooks-transaction",
      "thumbnailPath": "",
      "documentationPath": "/ballerina-integrator/shopify-to-quickbooks-transaction/README.md",
      "applications": ["Shopify", "QuickBooks"],
      "imageVersion": "0.1.0",
      "tags": [],
      "imageUrl": "wso2integrations.azurecr.io/shopify_to_quickbooks_transaction:0.2.0",
      "defaultPackage": "wso2/shopify_to_quickbooks_transaction",
      "bidirectional": false
    },
];
